name: Scrape Job Data

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggers from the GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests lxml

    - name: Run scraping script
      run: python scrape_jobs.py

    - name: Check if titles.json exists
      run: |
        if [ -f titles.json ]; then
          echo "titles.json exists!"
        else
          echo "titles.json is missing!" && exit 1
        fi

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add titles.json
        git commit -m "Update titles.json with latest job listings"
        git push
      continue-on-error: true  # Prevent failure if nothing to commit

    - name: List files in the directory
      run: ls -la
