name: Scrape Job Data

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggers from the GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Automatically handles git setup

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run scraping script
      run: python scrape_jobs.py  # This script scrapes jobs and creates 'oferty.json'

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add oferty.json
        git commit -m "Update oferty.json with latest job listings"
        git push
      continue-on-error: true  # Avoid failing the workflow if there are no changes
